import type { FreelancerProfile } from "../types/freelancer";

export const freelancers: FreelancerProfile[] = [
  {
    id: 1,
    name: "Adaeze Okonkwo",
    role: "Frontend Developer",
    category: "Development",
    location: "Lagos, NG",
    availability: "Available now",
    hourlyRate: "$32/hr",
    yearsExperience: 5,
    projectsCompleted: 46,
    rating: 4.9,
    bio: "Builds performant, conversion-focused web interfaces for startups and growth teams.",
    skills: ["React", "TypeScript", "Tailwind", "Vite"],
    email: "adaeze.okonkwo@jobton.dev",
    phone: "+2348103019001",
    handles: [
      { platform: "LinkedIn", href: "https://linkedin.com" },
      { platform: "Portfolio", href: "https://example.com/adaeze" },
      { platform: "X", href: "https://x.com" },
    ],
  },
  {
    id: 2,
    name: "Tunde Balogun",
    role: "UI/UX Designer",
    category: "Design",
    location: "Abuja, NG",
    availability: "Available next week",
    hourlyRate: "$28/hr",
    yearsExperience: 6,
    projectsCompleted: 52,
    rating: 4.8,
    bio: "Designs clean product experiences with strong usability and visual clarity.",
    skills: ["Figma", "Design Systems", "Prototyping", "User Research"],
    email: "tunde.balogun@jobton.dev",
    phone: "+2348117741200",
    handles: [
      { platform: "Portfolio", href: "https://example.com/tunde" },
      { platform: "Instagram", href: "https://instagram.com" },
    ],
  },
  {
    id: 3,
    name: "Fatima Yusuf",
    role: "Content Strategist",
    category: "Marketing",
    location: "Kano, NG",
    availability: "Available now",
    hourlyRate: "$24/hr",
    yearsExperience: 4,
    projectsCompleted: 39,
    rating: 4.7,
    bio: "Creates content funnels and editorial plans that drive qualified leads.",
    skills: ["SEO", "Copywriting", "Content Strategy", "Analytics"],
    email: "fatima.yusuf@jobton.dev",
    phone: "+2348129093414",
    handles: [
      { platform: "LinkedIn", href: "https://linkedin.com" },
      { platform: "X", href: "https://x.com" },
    ],
  },
  {
    id: 4,
    name: "Ifeanyi Nnamdi",
    role: "Backend Engineer",
    category: "Development",
    location: "Port Harcourt, NG",
    availability: "Limited availability",
    hourlyRate: "$35/hr",
    yearsExperience: 7,
    projectsCompleted: 61,
    rating: 4.9,
    bio: "Builds resilient APIs and scalable systems for fintech and SaaS products.",
    skills: ["Node.js", "PostgreSQL", "Redis", "System Design"],
    email: "ifeanyi.nnamdi@jobton.dev",
    phone: "+2348142215092",
    handles: [
      { platform: "Portfolio", href: "https://example.com/ifeanyi" },
      { platform: "LinkedIn", href: "https://linkedin.com" },
    ],
  },
  {
    id: 5,
    name: "Mariam Bello",
    role: "Virtual Assistant",
    category: "Operations",
    location: "Kaduna, NG",
    availability: "Available now",
    hourlyRate: "$18/hr",
    yearsExperience: 3,
    projectsCompleted: 33,
    rating: 4.6,
    bio: "Supports founders with admin workflows, scheduling, and customer communication.",
    skills: ["Calendar Management", "Notion", "Email Support", "CRM"],
    email: "mariam.bello@jobton.dev",
    phone: "+2348167801288",
    handles: [
      { platform: "WhatsApp", href: "https://wa.me/2348167801288" },
      { platform: "LinkedIn", href: "https://linkedin.com" },
    ],
  },
  {
    id: 6,
    name: "Kelechi Umeh",
    role: "Data Analyst",
    category: "Data",
    location: "Enugu, NG",
    availability: "Available next week",
    hourlyRate: "$29/hr",
    yearsExperience: 5,
    projectsCompleted: 41,
    rating: 4.8,
    bio: "Turns raw product and business data into actionable dashboards and insights.",
    skills: ["SQL", "Power BI", "Python", "A/B Testing"],
    email: "kelechi.umeh@jobton.dev",
    phone: "+2348134400719",
    handles: [
      { platform: "LinkedIn", href: "https://linkedin.com" },
      { platform: "Portfolio", href: "https://example.com/kelechi" },
    ],
  },
  {
    id: 7,
    name: "Sade Akin",
    role: "Social Media Manager",
    category: "Marketing",
    location: "Ibadan, NG",
    availability: "Available now",
    hourlyRate: "$22/hr",
    yearsExperience: 4,
    projectsCompleted: 48,
    rating: 4.7,
    bio: "Plans and executes social campaigns that improve engagement and brand recall.",
    skills: ["Content Planning", "Meta Ads", "Community", "Canva"],
    email: "sade.akin@jobton.dev",
    phone: "+2348172299180",
    handles: [
      { platform: "Instagram", href: "https://instagram.com" },
      { platform: "X", href: "https://x.com" },
    ],
  },
  {
    id: 8,
    name: "Chinedu Eze",
    role: "Mobile Developer",
    category: "Development",
    location: "Owerri, NG",
    availability: "Limited availability",
    hourlyRate: "$34/hr",
    yearsExperience: 6,
    projectsCompleted: 44,
    rating: 4.8,
    bio: "Delivers cross-platform mobile apps with polished UX and stable releases.",
    skills: ["React Native", "Expo", "Firebase", "App Store Release"],
    email: "chinedu.eze@jobton.dev",
    phone: "+2348185203366",
    handles: [
      { platform: "Portfolio", href: "https://example.com/chinedu" },
      { platform: "LinkedIn", href: "https://linkedin.com" },
    ],
  },
];
