import { useState } from "react";

export interface Job {
  id: number;
  company: string;
  domain: string;
  logo_url?: string | null;
  title: string;
  location: string;
  type: string;
  salary: string;
  status: string[];
  skills: string[];
  posted: string;
  saved?: boolean;
  applicants: number;
  datePosted: string;
  industry: string;
  experience: string;
  qualification: string;
  description: string;
  responsibilities: string[];
}

const jobsData: Job[] = [
  {
    id: 1,
    company: "Flutterwave",
    domain: "flutterwave.com",
    logo_url: null,
    title: "Senior Product Designer",
    location: "Lagos, Nigeria (Remote)",
    type: "Full Time",
    salary: "₦800,000 / month",
    status: ["verified"],
    skills: ["UI/UX", "Figma", "Product Strategy"],
    posted: "2 days ago",
    applicants: 15,
    datePosted: "May 20, 2026",
    industry: "Fintech",
    experience: "3–5 years",
    qualification: "B.Sc / HND",
    description:
      "We are looking for a talented Senior Product Designer to join our growing design team. You will work closely with product managers, engineers, and other designers to create intuitive, delightful, and impactful experiences for millions of users.",
    responsibilities: [
      "Design user-centered digital products and experiences",
      "Collaborate with cross-functional teams from ideation to launch",
      "Create wireframes, prototypes, and high-fidelity designs",
      "Conduct user research and usability testing",
      "Maintain and improve our design system",
    ],
  },
  {
    id: 2,
    company: "Google",
    domain: "google.com",
    logo_url: null,
    title: "Product Designer",
    location: "Lagos, Nigeria",
    type: "Full Time",
    salary: "$8,000 / month",
    status: ["featured", "verified"],
    skills: ["UI/UX", "Figma", "Research"],
    posted: "3 days ago",
    applicants: 30,
    datePosted: "May 19, 2026",
    industry: "Technology",
    experience: "4–6 years",
    qualification: "B.Sc",
    description:
      "Join Google's product design team and help shape the future of search and beyond. You will work on products used by billions of people worldwide.",
    responsibilities: [
      "Lead design for key product areas within Google Search",
      "Collaborate with cross-functional teams across time zones",
      "Conduct and synthesise user research",
      "Produce high-fidelity designs and prototypes",
    ],
  },
  {
    id: 3,
    company: "Microsoft",
    domain: "microsoft.com",
    logo_url: null,
    title: "UI/UX Designer",
    location: "Abuja, Nigeria",
    type: "On-site",
    salary: "₦500,000 / month",
    status: ["verified"],
    skills: ["Figma", "Azure", "UX Research"],
    posted: "3 days ago",
    applicants: 18,
    datePosted: "May 19, 2026",
    industry: "Technology",
    experience: "2–4 years",
    qualification: "B.Sc / HND",
    description:
      "Microsoft is hiring a UI/UX Designer to work on enterprise productivity tools. You will collaborate with engineers and PMs to deliver high-quality user experiences across Africa.",
    responsibilities: [
      "Design interfaces for Microsoft enterprise products",
      "Create and maintain the design system",
      "Partner with PMs and engineers to ship features",
      "Gather and act on user feedback",
    ],
  },
  {
    id: 4,
    company: "Meta",
    domain: "meta.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Contract",
    salary: "$2,000 – $2,500 / month",
    status: ["verified"],
    skills: ["React", "Figma", "Motion Design"],
    posted: "4 days ago",
    applicants: 42,
    datePosted: "May 18, 2026",
    industry: "Social Media",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Meta is seeking a Product Designer to work on next-generation social experiences. You will be part of a fully remote, globally distributed team shaping the future of connection.",
    responsibilities: [
      "Design features for Meta's social products",
      "Work closely with engineers on implementation",
      "Create prototypes and high-fidelity mockups",
      "Champion accessibility in all designs",
    ],
  },
  {
    id: 5,
    company: "Google",
    domain: 'google.com',
    logo_url: null,
    title: "Senior UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "₦900,000 / month",
    status: ["featured"],
    skills: ["UX Research", "Figma", "Prototyping"],
    posted: "5 days ago",
    applicants: 25,
    datePosted: "May 17, 2026",
    industry: "Technology",
    experience: "5+ years",
    qualification: "B.Sc",
    description:
      "We are looking for a Senior UX Designer to lead the design of Google's developer tools. You will shape the experience for millions of developers globally.",
    responsibilities: [
      "Lead UX for developer-facing products",
      "Define and drive design strategy",
      "Mentor junior designers on the team",
      "Champion user research as a core practice",
    ],
  },
  {
    id: 6,
    company: "Microsoft",
    domain: 'microsoft.com',
    logo_url: null,
    title: "Product Designer",
    location: "On-site",
    type: "Full Time",
    salary: "₦600,000 / month",
    status: ["verified"],
    skills: ["Figma", "Azure DevOps", "Sketch"],
    posted: "5 days ago",
    applicants: 10,
    datePosted: "May 17, 2026",
    industry: "Technology",
    experience: "2–3 years",
    qualification: "B.Sc / HND",
    description:
      "Join the Microsoft Nigeria team as a Product Designer, working on cloud productivity products that power businesses across Africa.",
    responsibilities: [
      "Create UX flows and wireframes",
      "Collaborate with engineers and PMs",
      "Contribute to the design system",
      "Present designs to key stakeholders",
    ],
  },
  {
    id: 7,
    company: "Spotify",
    domain: "spotify.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$6,500 / month",
    status: ["featured"],
    skills: ["Figma", "Design Systems", "Prototyping"],
    posted: "1 day ago",
    applicants: 12,
    datePosted: "May 21, 2026",
    industry: "Music Streaming",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Join Spotify's product design team to craft engaging experiences for millions of listeners worldwide.",
    responsibilities: [
      "Design intuitive user interfaces",
      "Collaborate with engineers and PMs",
      "Prototype new features",
      "Conduct usability testing",
    ],
  },
  {
    id: 8,
    company: "Netflix",
    domain: "netflix.com",
    logo_url: null,
    title: "Senior UI Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,800 / month",
    status: ["verified"],
    skills: ["UI Design", "Figma", "Interaction Design"],
    posted: "Today",
    applicants: 8,
    datePosted: "May 22, 2026",
    industry: "Entertainment",
    experience: "5+ years",
    qualification: "B.Sc",
    description:
      "Help shape the future of streaming experiences across TV, web, and mobile platforms.",
    responsibilities: [
      "Design high-quality interfaces",
      "Improve design systems",
      "Work closely with engineering",
      "Present concepts to stakeholders",
    ],
  },
  {
    id: 9,
    company: "Airbnb",
    domain: "airbnb.com",
    logo_url: null,
    title: "UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$6,900 / month",
    status: ["featured", "verified"],
    skills: ["Research", "Figma", "User Flows"],
    posted: "2 days ago",
    applicants: 20,
    datePosted: "May 20, 2026",
    industry: "Travel",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Design seamless booking and hosting experiences used by millions around the globe.",
    responsibilities: [
      "Create user journeys",
      "Conduct research",
      "Produce prototypes",
      "Collaborate across teams",
    ],
  },
  {
    id: 10,
    company: "Paystack",
    domain: "paystack.com",
    logo_url: null,
    title: "Product Designer",
    location: "Lagos, Nigeria",
    type: "Hybrid",
    salary: "₦950,000 / month",
    status: ["verified"],
    skills: ["Figma", "Design Systems", "UX"],
    posted: "Today",
    applicants: 6,
    datePosted: "May 22, 2026",
    industry: "Fintech",
    experience: "2–4 years",
    qualification: "B.Sc / HND",
    description:
      "Work with the Paystack team to build delightful payment experiences for African businesses.",
    responsibilities: [
      "Design new product features",
      "Collaborate with PMs",
      "Maintain design system",
      "Improve onboarding flows",
    ],
  },
  {
    id: 11,
    company: "Notion",
    domain: "notion.so",
    logo_url: null,
    title: "Visual Designer",
    location: "Remote",
    type: "Contract",
    salary: "$5,500 / month",
    status: ["featured"],
    skills: ["Brand Design", "Figma", "Illustration"],
    posted: "3 days ago",
    applicants: 15,
    datePosted: "May 19, 2026",
    industry: "Productivity",
    experience: "2–5 years",
    qualification: "B.Sc",
    description:
      "Help evolve Notion's visual language across product and marketing experiences.",
    responsibilities: [
      "Create polished UI visuals",
      "Design marketing assets",
      "Collaborate with product teams",
      "Maintain visual consistency",
    ],
  },
  {
    id: 12,
    company: "Canva",
    domain: "canva.com",
    logo_url: null,
    title: "Senior Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,200 / month",
    status: ["featured", "verified"],
    skills: ["Figma", "Design Systems", "UX Research"],
    posted: "Today",
    applicants: 11,
    datePosted: "May 22, 2026",
    industry: "Design Software",
    experience: "4–6 years",
    qualification: "B.Sc",
    description:
      "Join Canva's product team to build intuitive creative tools used by millions of people worldwide.",
    responsibilities: [
      "Design end-to-end product experiences",
      "Prototype and validate ideas",
      "Collaborate with engineers and PMs",
      "Improve the design system",
    ],
  },
  {
    id: 13,
    company: "Adobe",
    domain: "adobe.com",
    logo_url: null,
    title: "UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,800 / month",
    status: ["verified"],
    skills: ["Adobe XD", "Figma", "User Research"],
    posted: "1 day ago",
    applicants: 17,
    datePosted: "May 21, 2026",
    industry: "Software",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Design creative experiences across Adobe's suite of products with a focus on usability and innovation.",
    responsibilities: [
      "Create user flows and wireframes",
      "Conduct user research",
      "Build interactive prototypes",
      "Collaborate with engineering teams",
    ],
  },
  {
    id: 14,
    company: "Stripe",
    domain: "stripe.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$8,500 / month",
    status: ["featured"],
    skills: ["Figma", "Product Thinking", "Design Systems"],
    posted: "Today",
    applicants: 9,
    datePosted: "May 22, 2026",
    industry: "Fintech",
    experience: "4+ years",
    qualification: "B.Sc",
    description:
      "Help build financial infrastructure products that power businesses around the world.",
    responsibilities: [
      "Design payment experiences",
      "Collaborate with cross-functional teams",
      "Run design reviews",
      "Improve accessibility",
    ],
  },
  {
    id: 15,
    company: "Moniepoint",
    domain: "moniepoint.com",
    logo_url: null,
    title: "Product Designer",
    location: "Lagos, Nigeria",
    type: "Hybrid",
    salary: "₦1,100,000 / month",
    status: ["verified"],
    skills: ["Figma", "UX", "Design Systems"],
    posted: "2 days ago",
    applicants: 22,
    datePosted: "May 20, 2026",
    industry: "Fintech",
    experience: "3–5 years",
    qualification: "B.Sc / HND",
    description:
      "Work on digital banking products that empower businesses across Africa.",
    responsibilities: [
      "Design intuitive financial products",
      "Collaborate with product managers",
      "Create prototypes",
      "Maintain component libraries",
    ],
  },
  {
    id: 16,
    company: "Amazon",
    domain: "amazon.com",
    logo_url: null,
    title: "Senior UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$9,000 / month",
    status: ["featured", "verified"],
    skills: ["UX Research", "Figma", "Prototyping"],
    posted: "Today",
    applicants: 19,
    datePosted: "May 22, 2026",
    industry: "E-commerce",
    experience: "5+ years",
    qualification: "B.Sc",
    description:
      "Shape shopping experiences across Amazon's web and mobile platforms.",
    responsibilities: [
      "Lead UX initiatives",
      "Create high-fidelity designs",
      "Mentor designers",
      "Present design solutions",
    ],
  },
  {
    id: 17,
    company: "Shopify",
    domain: "shopify.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,100 / month",
    status: ["verified"],
    skills: ["Figma", "Interaction Design", "UX"],
    posted: "3 days ago",
    applicants: 14,
    datePosted: "May 19, 2026",
    industry: "E-commerce",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Design tools that help entrepreneurs build and grow online businesses.",
    responsibilities: [
      "Design merchant experiences",
      "Prototype product ideas",
      "Collaborate with engineers",
      "Improve design consistency",
    ],
  },
  {
    id: 18,
    company: "Interswitch",
    domain: "interswitchgroup.com",
    logo_url: null,
    title: "UI/UX Designer",
    location: "Lagos, Nigeria",
    type: "Full Time",
    salary: "₦850,000 / month",
    status: ["verified"],
    skills: ["Figma", "UX Research", "UI Design"],
    posted: "1 day ago",
    applicants: 13,
    datePosted: "May 21, 2026",
    industry: "Fintech",
    experience: "2–4 years",
    qualification: "B.Sc / HND",
    description:
      "Help create seamless payment and banking experiences for millions of users.",
    responsibilities: [
      "Design customer-facing interfaces",
      "Conduct usability testing",
      "Collaborate with engineering",
      "Maintain UI standards",
    ],
  },
  {
    id: 19,
    company: "Slack",
    domain: "slack.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Contract",
    salary: "$6,700 / month",
    status: ["featured"],
    skills: ["Figma", "Interaction Design", "Design Systems"],
    posted: "2 days ago",
    applicants: 18,
    datePosted: "May 20, 2026",
    industry: "Communication",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Design collaboration experiences that help teams communicate more effectively.",
    responsibilities: [
      "Design collaboration features",
      "Prototype workflows",
      "Run usability sessions",
      "Partner with engineering",
    ],
  },
  {
    id: 20,
    company: "Duolingo",
    domain: "duolingo.com",
    logo_url: null,
    title: "Visual Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$6,300 / month",
    status: ["verified"],
    skills: ["Visual Design", "Illustration", "Figma"],
    posted: "Today",
    applicants: 16,
    datePosted: "May 22, 2026",
    industry: "EdTech",
    experience: "2–4 years",
    qualification: "B.Sc",
    description:
      "Create delightful learning experiences for millions of language learners.",
    responsibilities: [
      "Design engaging interfaces",
      "Collaborate with researchers",
      "Prototype new concepts",
      "Improve visual consistency",
    ],
  },
  {
    id: 21,
    company: "GitHub",
    domain: "github.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$8,100 / month",
    status: ["featured", "verified"],
    skills: ["Figma", "Developer Tools", "UX"],
    posted: "Today",
    applicants: 7,
    datePosted: "May 22, 2026",
    industry: "Developer Tools",
    experience: "4–6 years",
    qualification: "B.Sc",
    description:
      "Help improve the experience for millions of developers building software together.",
    responsibilities: [
      "Design developer workflows",
      "Conduct user interviews",
      "Build prototypes",
      "Collaborate with engineering teams",
    ],
  },
  {
    id: 22,
    company: "LinkedIn",
    domain: "linkedin.com",
    logo_url: null,
    title: "Senior Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$8,300 / month",
    status: ["featured"],
    skills: ["Figma", "UX Research", "Design Systems"],
    posted: "Today",
    applicants: 9,
    datePosted: "May 22, 2026",
    industry: "Professional Networking",
    experience: "5+ years",
    qualification: "B.Sc",
    description:
      "Design products that help professionals connect, learn, and find opportunities worldwide.",
    responsibilities: [
      "Lead product design initiatives",
      "Conduct user research",
      "Create prototypes",
      "Collaborate with product and engineering",
    ],
  },
  {
    id: 23,
    company: "Uber",
    domain: "uber.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,900 / month",
    status: ["verified"],
    skills: ["Figma", "Interaction Design", "UX"],
    posted: "1 day ago",
    applicants: 15,
    datePosted: "May 21, 2026",
    industry: "Transportation",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Design intuitive experiences for riders, drivers, and merchants across Uber's platform.",
    responsibilities: [
      "Design user journeys",
      "Prototype new concepts",
      "Partner with engineers",
      "Validate designs through testing",
    ],
  },
  {
    id: 24,
    company: "Bolt",
    domain: "bolt.eu",
    logo_url: null,
    title: "UI/UX Designer",
    location: "Lagos, Nigeria",
    type: "Hybrid",
    salary: "₦780,000 / month",
    status: ["verified"],
    skills: ["Figma", "Wireframing", "User Research"],
    posted: "Today",
    applicants: 11,
    datePosted: "May 22, 2026",
    industry: "Mobility",
    experience: "2–4 years",
    qualification: "B.Sc / HND",
    description:
      "Help build seamless ride-hailing and delivery experiences for African users.",
    responsibilities: [
      "Design customer-facing features",
      "Work with cross-functional teams",
      "Prototype interfaces",
      "Maintain design quality",
    ],
  },
  {
    id: 25,
    company: "Figma",
    domain: "figma.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$8,900 / month",
    status: ["featured", "verified"],
    skills: ["Design Systems", "Prototyping", "UX"],
    posted: "Today",
    applicants: 5,
    datePosted: "May 22, 2026",
    industry: "Design Software",
    experience: "4–6 years",
    qualification: "B.Sc",
    description:
      "Help shape the future of collaborative design tools used by millions worldwide.",
    responsibilities: [
      "Design collaborative workflows",
      "Conduct usability research",
      "Prototype product ideas",
      "Work closely with engineers",
    ],
  },
  {
    id: 26,
    company: "Apple",
    domain: "apple.com",
    logo_url: null,
    title: "Interaction Designer",
    location: "Cupertino, CA",
    type: "Full Time",
    salary: "$10,500 / month",
    status: ["verified"],
    skills: ["Interaction Design", "SwiftUI", "Figma"],
    posted: "2 days ago",
    applicants: 28,
    datePosted: "May 20, 2026",
    industry: "Consumer Electronics",
    experience: "5+ years",
    qualification: "B.Sc",
    description:
      "Design elegant experiences across Apple's ecosystem of hardware and software.",
    responsibilities: [
      "Design product interactions",
      "Collaborate with engineering",
      "Present concepts to leadership",
      "Prototype experiences",
    ],
  },
  {
    id: 27,
    company: "X",
    domain: "x.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Contract",
    salary: "$6,800 / month",
    status: ["featured"],
    skills: ["Figma", "Motion Design", "UI Design"],
    posted: "3 days ago",
    applicants: 24,
    datePosted: "May 19, 2026",
    industry: "Social Media",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Design engaging social experiences for users around the world.",
    responsibilities: [
      "Design new platform features",
      "Prototype interactions",
      "Improve usability",
      "Collaborate with product teams",
    ],
  },
  {
    id: 28,
    company: "Oracle",
    domain: "oracle.com",
    logo_url: null,
    title: "UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,400 / month",
    status: ["verified"],
    skills: ["Figma", "Enterprise UX", "Research"],
    posted: "1 day ago",
    applicants: 12,
    datePosted: "May 21, 2026",
    industry: "Enterprise Software",
    experience: "4–6 years",
    qualification: "B.Sc",
    description:
      "Help modernize enterprise software experiences across Oracle Cloud.",
    responsibilities: [
      "Design enterprise interfaces",
      "Conduct user research",
      "Build prototypes",
      "Partner with product managers",
    ],
  },
  {
    id: 29,
    company: "Salesforce",
    domain: "salesforce.com",
    logo_url: null,
    title: "Senior UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$8,100 / month",
    status: ["featured"],
    skills: ["UX Strategy", "Figma", "Research"],
    posted: "Today",
    applicants: 10,
    datePosted: "May 22, 2026",
    industry: "CRM",
    experience: "5+ years",
    qualification: "B.Sc",
    description:
      "Design world-class CRM experiences for businesses of every size.",
    responsibilities: [
      "Lead UX strategy",
      "Prototype complex workflows",
      "Collaborate with engineers",
      "Mentor junior designers",
    ],
  },
  {
    id: 30,
    company: "Discord",
    domain: "discord.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,300 / month",
    status: ["verified"],
    skills: ["UI Design", "Figma", "Design Systems"],
    posted: "Today",
    applicants: 13,
    datePosted: "May 22, 2026",
    industry: "Communication",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Create engaging communication experiences for millions of communities worldwide.",
    responsibilities: [
      "Design messaging features",
      "Prototype new ideas",
      "Improve accessibility",
      "Collaborate across teams",
    ],
  },
  {
    id: 31,
    company: "Binance",
    domain: "binance.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,600 / month",
    status: ["featured", "verified"],
    skills: ["Figma", "Fintech", "UX"],
    posted: "2 days ago",
    applicants: 21,
    datePosted: "May 20, 2026",
    industry: "Blockchain",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Design intuitive experiences for global cryptocurrency and financial products.",
    responsibilities: [
      "Design trading interfaces",
      "Conduct user testing",
      "Create design specifications",
      "Collaborate with engineering teams",
    ],
  },
  {
    id: 32,
    company: "GitLab",
    domain: "gitlab.com",
    logo_url: null,
    title: "Senior Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$8,000 / month",
    status: ["verified"],
    skills: ["Design Systems", "Developer Tools", "Figma"],
    posted: "1 day ago",
    applicants: 8,
    datePosted: "May 21, 2026",
    industry: "Developer Tools",
    experience: "4–6 years",
    qualification: "B.Sc",
    description:
      "Join GitLab's all-remote team to build tools that empower software developers.",
    responsibilities: [
      "Design end-to-end developer experiences",
      "Lead UX initiatives",
      "Prototype features",
      "Collaborate asynchronously across teams",
    ],
  },
  {
    id: 33,
    company: "Wise",
    domain: "wise.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,000 / month",
    status: ["featured"],
    skills: ["Figma", "Fintech", "User Research"],
    posted: "Today",
    applicants: 14,
    datePosted: "May 22, 2026",
    industry: "Financial Services",
    experience: "3–5 years",
    qualification: "B.Sc",
    description:
      "Design fast, transparent international money transfer experiences for millions of customers.",
    responsibilities: [
      "Design customer journeys",
      "Improve onboarding flows",
      "Prototype new features",
      "Collaborate with engineering and research",
    ],
  },
  {
    id: 34,
    company: "Amazon",
    domain: "amazon.com",
    logo_url: null,
    title: "Senior Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,400 / month",
    status: ["featured"],
    skills: ["Figma", "Design Systems", "UX Research"],
    posted: "Today",
    applicants: 18,
    datePosted: "May 22, 2026",
    industry: "E-commerce",
    experience: "4–6 years",
    qualification: "B.Sc",
    description: "Design customer experiences across Amazon's shopping ecosystem.",
    responsibilities: [
      "Lead end-to-end product design",
      "Create prototypes",
      "Partner with engineers",
      "Improve customer journeys",
    ],
  },
  {
    id: 35,
    company: "Adobe",
    domain: "adobe.com",
    logo_url: null,
    title: "UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$6,800 / month",
    status: ["verified"],
    skills: ["Adobe XD", "Figma", "Research"],
    posted: "1 day ago",
    applicants: 12,
    datePosted: "May 21, 2026",
    industry: "Software",
    experience: "3–5 years",
    qualification: "B.Sc",
    description: "Join Adobe's experience design team building creative tools.",
    responsibilities: [
      "Conduct UX research",
      "Design workflows",
      "Prototype interfaces",
      "Work with engineering teams",
    ],
  },
  {
    id: 36,
    company: "Canva",
    domain: "canva.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$6,200 / month",
    status: ["featured", "verified"],
    skills: ["Figma", "Interaction Design", "UI"],
    posted: "2 days ago",
    applicants: 22,
    datePosted: "May 20, 2026",
    industry: "Design Software",
    experience: "3–5 years",
    qualification: "B.Sc",
    description: "Help millions create beautiful designs with Canva.",
    responsibilities: [
      "Design new editor features",
      "Collaborate with PMs",
      "Improve usability",
      "Build prototypes",
    ],
  },
  {
    id: 37,
    company: "Stripe",
    domain: "stripe.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$8,200 / month",
    status: ["verified"],
    skills: ["Figma", "Design Systems", "Fintech"],
    posted: "Today",
    applicants: 11,
    datePosted: "May 22, 2026",
    industry: "Fintech",
    experience: "4+ years",
    qualification: "B.Sc",
    description: "Design payment experiences for businesses worldwide.",
    responsibilities: [
      "Design payment flows",
      "Create prototypes",
      "Conduct user testing",
      "Collaborate cross-functionally",
    ],
  },
  {
    id: 38,
    company: "Moniepoint",
    domain: "moniepoint.com",
    logo_url: null,
    title: "Senior UX Designer",
    location: "Lagos, Nigeria",
    type: "Hybrid",
    salary: "₦1,100,000 / month",
    status: ["featured"],
    skills: ["UX", "Figma", "Research"],
    posted: "Today",
    applicants: 9,
    datePosted: "May 22, 2026",
    industry: "Fintech",
    experience: "5+ years",
    qualification: "B.Sc / HND",
    description: "Improve financial experiences for businesses across Africa.",
    responsibilities: [
      "Lead UX initiatives",
      "Conduct research",
      "Mentor designers",
      "Improve onboarding flows",
    ],
  },
  {
    id: 39,
    company: "Interswitch",
    domain: "interswitchgroup.com",
    logo_url: null,
    title: "UI Designer",
    location: "Lagos, Nigeria",
    type: "Full Time",
    salary: "₦750,000 / month",
    status: ["verified"],
    skills: ["UI Design", "Figma", "Illustrator"],
    posted: "3 days ago",
    applicants: 17,
    datePosted: "May 19, 2026",
    industry: "Fintech",
    experience: "2–4 years",
    qualification: "B.Sc",
    description: "Design digital banking experiences for African users.",
    responsibilities: [
      "Design interfaces",
      "Maintain UI consistency",
      "Collaborate with developers",
      "Review usability",
    ],
  },
  {
    id: 40,
    company: "GitHub",
    domain: "github.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,000 / month",
    status: ["featured"],
    skills: ["Figma", "Developer Tools", "UX"],
    posted: "1 day ago",
    applicants: 14,
    datePosted: "May 21, 2026",
    industry: "Developer Tools",
    experience: "3–5 years",
    qualification: "B.Sc",
    description: "Shape the future of software collaboration.",
    responsibilities: [
      "Design developer experiences",
      "Prototype workflows",
      "Collaborate with PMs",
      "Run usability studies",
    ],
  },
  {
    id: 41,
    company: "Slack",
    domain: "slack.com",
    logo_url: null,
    title: "UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$6,700 / month",
    status: ["verified"],
    skills: ["Research", "UI", "Figma"],
    posted: "2 days ago",
    applicants: 16,
    datePosted: "May 20, 2026",
    industry: "Communication",
    experience: "3+ years",
    qualification: "B.Sc",
    description: "Design collaborative workplace experiences.",
    responsibilities: [
      "Improve messaging UX",
      "Prototype features",
      "Conduct user interviews",
      "Support design system",
    ],
  },
  {
    id: 42,
    company: "Dropbox",
    domain: "dropbox.com",
    logo_url: null,
    title: "Senior UI Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$6,900 / month",
    status: ["featured"],
    skills: ["UI", "Design Systems", "Figma"],
    posted: "4 days ago",
    applicants: 20,
    datePosted: "May 18, 2026",
    industry: "Cloud Storage",
    experience: "5+ years",
    qualification: "B.Sc",
    description: "Design productivity tools used by millions.",
    responsibilities: [
      "Lead interface design",
      "Create reusable components",
      "Collaborate with engineers",
      "Present design reviews",
    ],
  },
  {
    id: 43,
    company: "Oracle",
    domain: "oracle.com",
    logo_url: null,
    title: "Product Designer",
    location: "Abuja, Nigeria",
    type: "Hybrid",
    salary: "₦850,000 / month",
    status: ["verified"],
    skills: ["UX", "Figma", "Enterprise Design"],
    posted: "Today",
    applicants: 13,
    datePosted: "May 22, 2026",
    industry: "Enterprise Software",
    experience: "3–5 years",
    qualification: "B.Sc",
    description: "Design enterprise cloud products for business customers.",
    responsibilities: [
      "Design enterprise dashboards",
      "Collaborate with PMs",
      "Validate concepts",
      "Improve accessibility",
    ],
  },
  {
    id: 44,
    company: "Salesforce",
    domain: "salesforce.com",
    logo_url: null,
    title: "UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,300 / month",
    status: ["featured", "verified"],
    skills: ["Research", "Figma", "CRM"],
    posted: "Today",
    applicants: 7,
    datePosted: "May 22, 2026",
    industry: "CRM",
    experience: "4–6 years",
    qualification: "B.Sc",
    description: "Design customer relationship management experiences.",
    responsibilities: [
      "Improve workflows",
      "Conduct user research",
      "Prototype solutions",
      "Work with engineers",
    ],
  },
  {
    id: 45,
    company: "Asana",
    domain: "asana.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Contract",
    salary: "$5,900 / month",
    status: ["verified"],
    skills: ["Figma", "UX", "Prototyping"],
    posted: "5 days ago",
    applicants: 15,
    datePosted: "May 17, 2026",
    industry: "Productivity",
    experience: "3–5 years",
    qualification: "B.Sc",
    description: "Design features that help teams work better together.",
    responsibilities: [
      "Design collaboration tools",
      "Build prototypes",
      "Conduct research",
      "Partner with product teams",
    ],
  },
  {
    id: 46,
    company: "Shopify",
    domain: "shopify.com",
    logo_url: null,
    title: "Senior Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,500 / month",
    status: ["featured"],
    skills: ["Commerce", "Figma", "UX"],
    posted: "2 days ago",
    applicants: 19,
    datePosted: "May 20, 2026",
    industry: "E-commerce",
    experience: "5+ years",
    qualification: "B.Sc",
    description: "Help merchants succeed with world-class commerce experiences.",
    responsibilities: [
      "Lead product design",
      "Improve merchant tools",
      "Prototype ideas",
      "Collaborate with engineering",
    ],
  },
  {
    id: 47,
    company: "LinkedIn",
    domain: "linkedin.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,100 / month",
    status: ["verified"],
    skills: ["Figma", "Research", "Interaction Design"],
    posted: "Today",
    applicants: 10,
    datePosted: "May 22, 2026",
    industry: "Professional Networking",
    experience: "3–5 years",
    qualification: "B.Sc",
    description: "Design experiences that connect professionals globally.",
    responsibilities: [
      "Design networking features",
      "Conduct usability testing",
      "Collaborate cross-functionally",
      "Create design specs",
    ],
  },
  {
    id: 48,
    company: "Palantir",
    domain: "palantir.com",
    logo_url: null,
    title: "UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$8,500 / month",
    status: ["featured"],
    skills: ["Enterprise UX", "Figma", "Research"],
    posted: "3 days ago",
    applicants: 8,
    datePosted: "May 19, 2026",
    industry: "Data Analytics",
    experience: "5+ years",
    qualification: "B.Sc",
    description: "Design mission-critical software for enterprise customers.",
    responsibilities: [
      "Design complex workflows",
      "Conduct user interviews",
      "Prototype interfaces",
      "Support product strategy",
    ],
  },
  {
    id: 49,
    company: "Bolt",
    domain: "bolt.eu",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$5,800 / month",
    status: ["verified"],
    skills: ["Figma", "Mobility", "UX"],
    posted: "Yesterday",
    applicants: 12,
    datePosted: "May 21, 2026",
    industry: "Mobility",
    experience: "3–5 years",
    qualification: "B.Sc",
    description: "Design ride-hailing and mobility experiences.",
    responsibilities: [
      "Design mobile features",
      "Improve booking flow",
      "Run usability tests",
      "Collaborate with engineers",
    ],
  },
  {
    id: 50,
    company: "Duolingo",
    domain: "duolingo.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$6,400 / month",
    status: ["featured", "verified"],
    skills: ["Gamification", "Figma", "UI"],
    posted: "Today",
    applicants: 21,
    datePosted: "May 22, 2026",
    industry: "EdTech",
    experience: "3–5 years",
    qualification: "B.Sc",
    description: "Create delightful language-learning experiences.",
    responsibilities: [
      "Design engaging lessons",
      "Prototype new ideas",
      "Conduct research",
      "Collaborate with product teams",
    ],
  },
  {
    id: 51,
    company: "Zoom",
    domain: "zoom.us",
    logo_url: null,
    title: "Senior UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$7,200 / month",
    status: ["verified"],
    skills: ["Figma", "Accessibility", "UX"],
    posted: "2 days ago",
    applicants: 11,
    datePosted: "May 20, 2026",
    industry: "Communication",
    experience: "5+ years",
    qualification: "B.Sc",
    description: "Help improve video communication experiences worldwide.",
    responsibilities: [
      "Lead UX projects",
      "Improve meeting workflows",
      "Create prototypes",
      "Mentor designers",
    ],
  },
  {
    id: 52,
    company: "Figma",
    domain: "figma.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$8,000 / month",
    status: ["featured"],
    skills: ["Design Systems", "Figma", "Prototyping"],
    posted: "Today",
    applicants: 26,
    datePosted: "May 22, 2026",
    industry: "Design Software",
    experience: "4–6 years",
    qualification: "B.Sc",
    description: "Build the future of collaborative design tools.",
    responsibilities: [
      "Design new editor capabilities",
      "Prototype experiences",
      "Collaborate with engineers",
      "Improve design workflows",
    ],
  },
  {
    id: 53,
    company: "Revolut",
    domain: "revolut.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$6,900 / month",
    status: ["verified"],
    skills: ["Fintech", "UX", "Figma"],
    posted: "Yesterday",
    applicants: 14,
    datePosted: "May 21, 2026",
    industry: "Fintech",
    experience: "3–5 years",
    qualification: "B.Sc",
    description: "Design modern financial experiences for global users.",
    responsibilities: [
      "Design fintech products",
      "Validate user flows",
      "Create mockups",
      "Work with PMs",
    ],
  },
  {
    id: 54,
    company: "HubSpot",
    domain: "hubspot.com",
    logo_url: null,
    title: "UX Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$6,300 / month",
    status: ["featured"],
    skills: ["CRM", "Research", "Figma"],
    posted: "4 days ago",
    applicants: 18,
    datePosted: "May 18, 2026",
    industry: "Marketing Software",
    experience: "3–5 years",
    qualification: "B.Sc",
    description: "Design tools that help businesses grow.",
    responsibilities: [
      "Design CRM experiences",
      "Run user testing",
      "Prototype concepts",
      "Improve accessibility",
    ],
  },
  {
    id: 55,
    company: "Andela",
    domain: "andela.com",
    logo_url: null,
    title: "Product Designer",
    location: "Remote",
    type: "Full Time",
    salary: "$4,800 / month",
    status: ["verified"],
    skills: ["UX", "Figma", "Remote Collaboration"],
    posted: "Today",
    applicants: 29,
    datePosted: "May 22, 2026",
    industry: "Talent Marketplace",
    experience: "2–4 years",
    qualification: "B.Sc / HND",
    description: "Design experiences that connect global talent with companies.",
    responsibilities: [
      "Improve hiring flows",
      "Create design assets",
      "Collaborate with product",
      "Conduct research",
    ],
  },
  {
    id: 56,
    company: "Opay",
    domain: "opayweb.com",
    logo_url: null,
    title: "UI/UX Designer",
    location: "Lagos, Nigeria",
    type: "Full Time",
    salary: "₦850,000 / month",
    status: ["featured", "verified"],
    skills: ["Figma", "UI", "UX"],
    posted: "Today",
    applicants: 24,
    datePosted: "May 22, 2026",
    industry: "Fintech",
    experience: "3–5 years",
    qualification: "B.Sc / HND",
    description: "Design secure and intuitive financial products for millions of users.",
    responsibilities: [
      "Design mobile banking features",
      "Create prototypes",
      "Conduct UX research",
      "Collaborate with engineering",
    ],
  },
];

export const useJobs = () => {
  const [jobs] = useState<Job[]>(jobsData);
  return { jobs };
};
